### ISSUE TITLE
False positive unused variables warning inside CEs

### ISSUE THREAD

**Issue by MangelMaxime** [JetBrains/resharper-fsharp#467] opened 2022-12-30 14:34 UTC
I am using [SqlHydra](https://github.com/JordanMarr/SqlHydra) in one of my project. It uses CEs to build SQL queries and I found out that Rider report `unused` variables inside CEs even if they are used.

`person` and `account` are reported unused when they are actually used.

<img width="696" alt="image" src="https://user-images.githubusercontent.com/4760796/210081174-82604701-d5a5-4ee8-9007-20cd4031fd01.png">

On simpler query without join the warning goes away:

<img width="564" alt="image" src="https://user-images.githubusercontent.com/4760796/210081296-d469511f-f7b6-4053-b868-5ea211184cc0.png">

I was able to reproduce the problem using Linq CE syntax:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/4760796/210081391-a3c27ca6-38f3-4622-9f19-14e736c8011f.png">

Both `place` and `place1` are reported unused.

```fs
let people = [
      ("Tomas", 1)
      ("Joe", 2)
      ("Don", 1)
  ]

  let places = [
      (1, "Cambridge")
      (2, "Wisconsin")
  ]

  let x = query {
      for person in people do
          join place in places on (snd person = fst place)
          join place1 in places on (snd person = fst place1) 
          select (fst person, snd place)
  }
```

**Comment by edgarfgp** [comment] 2022-12-30 14:42
Same happens when using  SQLProvider

**Comment by auduchinok** [comment] 2023-01-09 15:51
@MangelMaxime Thank you for reporting this. This warning is produced by FCS, and I've created an issue there: https://github.com/dotnet/fsharp/issues/14566

**Comment by auduchinok** [comment] 2023-01-09 15:52
@edgarfgp Could you share any example, please? Preferably, in the F# repo.

**Comment by auduchinok** [comment] 2023-01-09 15:54
I'll close this issue, let's discuss it in the linked one instead.

**Closed by auduchinok** 2023-01-09 15:54 UTC

**Comment by auduchinok** [comment] 2023-09-06 14:38
I've pushed a temporary workaround on our side, until the issue is fixed in FCS.

**Comment by MangelMaxime** [comment] 2023-09-06 15:17
Awesome thank you @auduchinok
